const TestOrder = {
  id: "12345678910",
  test: true,
  app_id: "routeMagnet",
  cancel_reason: null,
  cancelled_at: null,
  currency: "CAD",
  current_total_price: "35.0",
  total_price: "35.0",
  email: null,
  order_status_url: "https://domain/order/12345678910",
  shipping_address: {
    first_name: "Joe",
    address1: "1600 Rene-Levesque Blvd W",
    phone: "+12345678914",
    city: "Montreal",
    zip: "H3H1P9",
    province: "QC",
    country: "Canada",
    last_name: "Pify",
    address2: "",
    company: "AutoHebdo",
    latitude: 45.49345,
    longitude: -73.57499,
    name: "Joe Pify",
    country_code: "Canada",
    province_code: "QC",
  },
  customer: { email: null, phone: "+14389249441" },
  shipping_lines: [
    {
      id: "gid://shopify/ShippingLine/3238983729323",
      carrier_identifier: null,
      code: "Local Delivery",
      delivery_category: null,
      discounted_price: "0.0",
      phone: "+14389249441",
      price: "0.0",
      quantity: 1,
      source: "shopify",
      title: "Local Delivery",
    },
  ],
  line_items: [
    {
      id: "gid://shopify/LineItem/9894192414891",
      title: "Long Sleeve Cotton Top",
      quantity: 1,
      price: "35.0",
      name: "Long Sleeve Cotton Top - large",
    },
  ],
};
export { TestOrder };
